# Generated by Django 5.0 on 2024-03-02 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='nid',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
