# Generated by Django 5.0 on 2024-03-05 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nid',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
