# Generated by Django 5.0 on 2024-03-13 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat_formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, choices=[('6:00 AM', '6:00 AM'), ('12:00 PM', '12:00 PM'), ('3:00 PM', '3:00 PM'), ('8:00 PM', '8:00 PM')], max_length=15, null=True)),
                ('seat', models.CharField(blank=True, choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=15, null=True)),
                ('seat_number', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('destination', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Sunamganj', 'Sunamganj'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=200, null=True)),
                ('seat_formation', models.ManyToManyField(to='train.seat_formation')),
                ('station', models.ManyToManyField(to='train.station')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_acc', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.train_list')),
            ],
        ),
    ]
