# Generated by Django 5.0 on 2024-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='train_list',
            name='destination',
            field=models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='train_list',
            name='seat',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='train_list',
            name='time',
            field=models.CharField(blank=True, choices=[('6:00 AM', '6:00 AM'), ('12:00 PM', '12:00 PM'), ('3:00 PM', '3:00 PM'), ('8:00 PM', '8:00 PM')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='train_list',
            name='station',
            field=models.ManyToManyField(to='train.station'),
        ),
    ]
