# Generated by Django 5.0 on 2024-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_station_train_list_destination_train_list_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_list',
            name='seat_number',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=200, null=True),
        ),
    ]
