# Generated by Django 5.0 on 2024-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_train_list_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_list',
            name='destination',
            field=models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Sunamganj', 'Sunamganj'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='train_list',
            name='seat_number',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=5, null=True),
        ),
    ]
