# Generated by Django 5.0 on 2024-03-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_alter_train_list_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_list',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
