# Generated by Django 5.0 on 2024-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_remove_train_list_seat_layout_train_list_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_list',
            name='seats',
            field=models.CharField(blank=True, help_text="Enter seats in the format 'a1 a2 b1 b2 c1 c2'", max_length=100, null=True),
        ),
    ]
